### ISSUE TITLE
Version `0.7.4` break onboard camera support

### ISSUE THREAD

**Issue by itnok** [Sniki/OS-X-USB-Inject-All#6] opened 2020-03-19 00:04 UTC
Version tagged `0.7.4` break onboard camera support on my Lenovo X1 Carbon 6th Gen.

Camera is recognized as USB3 and presented among USB devices by not recognized as a camera by the OS. It also looks like it is interfering with the bluetooth kext somehow as BT connections are not happening anymore or are flaky. _(using DW-1820a via [`BrcmPatchRAM3 kext`](https://github.com/acidanthera/BrcmPatchRAM))_

Reverting to `v0.7.3` solves all the problems.

**Comment by Sniki** [comment] 2020-03-20 01:39
> Version tagged `0.7.4` break onboard camera support on my Lenovo X1 Carbon 6th Gen.
> 
> Camera is recognized as USB3 and presented among USB devices by not recognized as a camera by the OS. It also looks like it is interfering with the bluetooth kext somehow as BT connections are not happening anymore or are flaky. _(using DW-1820a via [`BrcmPatchRAM3 kext`](https://github.com/acidanthera/BrcmPatchRAM))_
> 
> Reverting to `v0.7.3` solves all the problems.

A regression on my side, that's why i did pull back the 0.7.4 release on the release tab.

If all goes well, i may be able to update this weekend.

Thanks !

**Comment by Sniki** [comment] 2020-03-22 12:58
@itnok i did release the 0.7.5 update on master.
If you can build from source, please give it a try and let me know if the problem is resolved.

Update: Release added into Release Tab as well, you can grab prebuilt kexts.

Thanks !

**Comment by itnok** [comment] 2020-03-22 20:01
Hey @Sniki, just tried to build from source and install the Kext on my laptop. Few comments/observations about it:

- There are several warnings that can easily be fixed _(on my side I fixed them before building)_;
- The tagged version is not SemVer compliant _(it should be either `0.7.5` or `v0.7.5` in the past was used `vX.Y.Z` format... i'd stick with that)_
- The Kext builds regularly and after the boot my camera is correctly supported, but bluetooth is toast _(my headphones can connect, but no audio or mic input work anymore as opposed they were correctly working on `v0.7.3`)_

Will revert once again to `v0.7.3`, because at the moment is the most stable and the one giving me a more well-behaved setup _(at least on my machine)_

Thank you for the work you are putting on this kext!
Let me know if you need me to eventually do more testing _(very happy to!)_

**Comment by Sniki** [comment] 2020-03-24 19:14
> There are several warnings that can easily be fixed (on my side I fixed them before building);

Yes im aware of them but it's those warnings that broke 0.7.4 so i decided to not bother about them, they are just warnings anyway.
> The tagged version is not SemVer compliant (it should be either 0.7.5 or v0.7.5 in the past was used vX.Y.Z format... i'd stick with that)

Fixed that, thanks for the tip.
> The Kext builds regularly and after the boot my camera is correctly supported, but bluetooth is toast (my headphones can connect, but no audio or mic input work anymore as opposed they were correctly working on v0.7.3)

Hmm, it's really weird, i don't see anything at all that can brake that, the only change is OSSafeRelease that now is updated to OSSafeReleaseNULL which is an updated code as OSSafeRelease is deprecated in favor of OSSafeReleaseNULL.

**Comment by itnok** [comment] 2020-03-24 19:20
Thanks for the feedback!

I will give it another try later today without fixing the warnings _(could it be the problem as you experienced in `0.7.4`?)_.

Will report here later...

**Comment by Sniki** [comment] 2020-03-25 09:39
> Thanks for the feedback!
> 
> I will give it another try later today without fixing the warnings _(could it be the problem as you experienced in `0.7.4`?)_.
> 
> Will report here later...

Yes, the problem for me where the warnings.

Are you running Catalina or Mojave ?
I just got an issue about people complaining they cant mount external drives.
If you have one, can you please test it, i currently am downloading Mojave and will install it on one of my Hackintosh machines so i can verify those problems.

As usually you can expect people complain such things while they may not have generated properly a Custom SSDT and use just the port limit patch which is not recommended and can introduce issues.

**Comment by itnok** [comment] 2020-03-25 16:21
Rebuilt ignoring warnings _(just changed target platform from 10.11 to 10.14)_ and after the reboot **everything works fine** _(am sorry I also upgraded Lilu & Whatevergreen though to the latest versions available today, so the test might be not completely proper)_.

Am currently on Catalina _(`10.15.3`)_. Currently not experiencing any problem whatsoever mounting external drives connected to USB ports _(both type A and type C)_. Tested with a Samsung T5 drive.

Will do some more tests probably _(warnings really bother me... always 😊 !)_

**Comment by Sniki** [comment] 2020-03-25 16:34
> Rebuilt ignoring warnings _(just changed target platform from 10.11 to 10.14)_ and after the reboot **everything works fine** _(am sorry I also upgraded Lilu & Whatevergreen though to the latest versions available today, so the test might be not completely proper)_.
> 
> Am currently on Catalina _(`10.15.3`)_. Currently not experiencing any problem whatsoever mounting external drives connected to USB ports _(both type A and type C)_. Tested with a Samsung T5 drive.
> 
> Will do some more tests probably _(warnings really bother me... always 😊 !)_

Nice, so without touching the warnings your bluetooth works correctly on latest version.

I downloaded latest macOS Mojave and updated my Lenovo ThinkPad X240 project.
Will install Mojave and test that issue, so it's not applicable to Catalina thanks to your confirmation and assume the same on Mojave but will try and confirm that myself for Mojave.

Thank you for the testing and confirmation.

Will close this but feel free to re-open / open new issue whatever other problem you face.

Respect,
Sniki

**Closed as completed by Sniki** 2020-03-25 16:34 UTC
