### ISSUE TITLE
Versionup 0.7.3 to 0.7.5. Mojave can't mount USB-HDD Drive

### ISSUE THREAD

**Issue by mifjpn** [Sniki/OS-X-USB-Inject-All#7] opened 2020-03-25 08:05 UTC
Thank you for useful kext.
When I version up 0.7.3 to 0.7.5, Mojave can't mount USB-HDD(external) Drive.
Is there any good way?

**Comment by vacarogit** [comment] 2020-03-25 09:22
Second to that, seems this 075 is not abe to load, plz fix thank

**Comment by cryo-kronos** [comment] 2020-04-01 21:42
Also seeing this. Had to revert to 0.7.3. The recent security patch seems to have broken it. I'm on Mojave 10.14.6.

**Comment by Sniki** [comment] 2020-04-01 21:49
Will install macOS on one of my devices and test / verify the source of the problem.

**Comment by najdanovicivan** [comment] 2020-04-10 21:07
Won't load

```
2020-04-10 23:02:12.231557+0200  localhost kernel[0]: kxld[com.rehabman.driver.USBInjectAll]: The super class vtable '__ZTV9IOService' for vtable '__ZTV12USBInjectAll' is out of date. Make sure your kext has been built against the correct headers.
2020-04-10 23:02:12.247098+0200  localhost kernel[0]: kxld[com.rehabman.driver.USBInjectAll]: The super class vtable '__ZTV9IOService' for vtable '__ZTV19USBInjectAll_config' is out of date. Make sure your kext has been built against the correct headers.
2020-04-10 23:02:12.249470+0200  localhost kernel[0]: Can't load kext com.rehabman.driver.USBInjectAll - link failed.
2020-04-10 23:02:12.251469+0200  localhost kernel[0]: Failed to load executable for kext com.rehabman.driver.USBInjectAll.
2020-04-10 23:02:12.253270+0200  localhost kernel[0]: Kext com.rehabman.driver.USBInjectAll failed to load (0xdc008016).
2020-04-10 23:02:12.255224+0200  localhost kernel[0]: Failed to load kext com.rehabman.driver.USBInjectAll (error 0xdc008016).
2020-04-10 23:02:12.332091+0200  localhost kernel[0]: Couldn't alloc class "USBInjectAll_config"
```

**Comment by Sniki** [comment] 2020-04-12 14:24
Im aware of the issue and im working on it, fix should be available into next release.
For now use the 0.7.3 or 0.7.2

**Comment by kprinssu** [comment] 2020-04-12 15:07
Try the following attached kext, [Release.zip](https://github.com/Sniki/OS-X-USB-Inject-All/files/4466534/Release.zip). This has been built with 10.12 and should work on 10.12+.

Here's the command I used to download and install the macOS 10.12 SDK to Xcode`curl -L https://github.com/alexey-lysiuk/macos-sdk/releases/download/10.12/MacOSX10.12.tar.bz2 -o /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.tar.bz2 && sudo tar -xjf /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.12.tar.bz2 -C /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/`

The SDK package is the same one that VoodooI2C uses for CI builds. Next when you are building the project, you need to change the SDK version by going to Xcode -> Project (blue icon on the left sidebar) -> Build Settings -> Base SDK. Set the value of Base SDK to macOS 10.12 in the dropdown.

The issue is that the kext built by @Sniki  has been built with a newer SDK and thus won't load on older macOS versions due to incompatible binaries (linking fails as the error states above in @najdanovicivan log).

**Comment by mifjpn** [comment] 2020-04-12 17:46
I commend you for your contribution to the issue.
I hope your contribution will be successful.

**Comment by najdanovicivan** [comment] 2020-04-16 16:28
@kprinssu 

I can confirm that your build works properly.

**Comment by mifjpn** [comment] 2020-04-17 21:07
Me too.
Thank you.

**Comment by f00b4r0** [comment] 2020-07-01 17:39
@kprinssu's build working for me on 10.14.6 w/ OpenCore

**Comment by Sniki** [comment] 2020-07-01 20:01
Updating USBInjectAll.kext is in my To Do list for a bigger update and cleanup however i can't give any ETA for now as Summer is the most Busy season for me.

**Comment by mifjpn** [comment] 2020-07-02 09:39
Work is important. Good luck

**Comment by mifjpn** [comment] 2020-07-02 10:10
Instead, I used Hackintool to create UsbPorts.kext. It limits UsbPort to 15. However, since it depends on the model ID, adjustment is necessary.

**Comment by dateno1** [comment] 2020-07-04 10:02
Maybe Same Problem

Dell Latitude 12 E7250 Touch Screen not work with 0.7.4 or 0.7.5 (work with 0.7.3)

It connected with USB

Tested on Mojave 10.14.6 Lastest (maybe update it to Catalina 10.15.5 today)

I waiting for update

**Comment by Sniki** [comment] 2021-04-01 19:49
This will be fixed with the migration of MacKernelSDK library from Acidanthera.
For now i have no ETA on when i will be able to address this, limited on time for now, unless someone wants to do this and address it with a Pull Request.

"Somewhere after summer maybe"

**Closed as completed** 2021-04-02 07:33 UTC
